<a href="https://colab.research.google.com/github/Yashthon/Numpy/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Consider this URL: https://www.kaggle.com/utsav15/100-numpy-exercises
# exercises, execute all the examples and write your observations.

In [1]:
import numpy as np # importing numpy as np

In [3]:
print(np.__version__) # checking the version
np.show_config() # to show configurations

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [5]:
# Creating null vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# find the memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize)) # it shows the memory size of the array in bytes

800 bytes


In [8]:
# get the documentation of the numpy add function from the command line
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


In [9]:
# Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
# Create a vector with values ranging from 10 to 49 
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
# Reverse a vector (first element becomes last)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [12]:
#  Create a 3x3 matrix with values ranging from 0 to 8 
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4]),)


In [14]:
# Create a 3x3 identity matrix
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
print(Z)

[[[0.35559086 0.89249367 0.2469871 ]
  [0.74976156 0.38341125 0.49249497]
  [0.61503894 0.30571361 0.88022045]]

 [[0.71367259 0.84886922 0.08701247]
  [0.18064793 0.06929716 0.76866961]
  [0.96535493 0.24318571 0.27698249]]

 [[0.16676458 0.97180562 0.24738364]
  [0.23619764 0.61282846 0.04453759]
  [0.15453495 0.27379443 0.44080586]]]


In [16]:
# Create a 10x10 array with random values and find the minimum and maximum values 
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.003069245512893115 0.9985187658606728


In [17]:
# Create a random vector of size 30 and find the mean value 
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5323784808242009


In [18]:
# Create a 2d array with 1 on the border and 0 inside 
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
# How to add a border (filled with 0's) around an existing array?
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [22]:
# What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [23]:
#  Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [24]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [25]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [26]:
# Create a checkerboard 8x8 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
# Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.272878   -0.36650693 -1.65599562  0.66314593 -1.99102309]
 [ 0.33104042  1.24709    -0.52025942 -0.97390058  0.62541348]
 [-0.94040394  1.4160277  -0.53719611  1.31537789  0.66072574]
 [-1.10478128  0.28832859 -0.080211    0.89264817  1.52918125]
 [ 0.02680484 -0.82057897 -1.67848952  0.46870895  0.93197547]]


In [32]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [33]:
#  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [35]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [36]:
# Given a 1D array, negate all elements which are between 3 and 8, in place. 
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [37]:
# What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [1]:
# Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

In [2]:
# What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

NameError: ignored

In [ ]:
# How to round away from zero a float array ?


# 2. Consider this URL:
# https://www.hackerrank.com/domains/python/numpy/difficulty:eas
# y/page:1, execute all the examples related to numpy. Write your
# observations.

In [3]:
# Arrays
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    numpy_arr = numpy.array(arr, float)
    return numpy_arr

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [4]:
# Shape and Reshape arrays
import numpy as np
print(np.array(input().split(), int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Transpose and flatten
import numpy as np
n,m = map(int, input().split())
a = np.array([input().strip().split()for _ in range(n)], int)
print (a.transpose())
print (a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [9]:
# Concatenate
import numpy as np
n,m,p = map(int,input().split())

lista1=[list(map(int,input().split())) for i in range(n)]
lista2=[list(map(int,input().split())) for i in range(m)]
a1=np.array(lista1)
a2=np.array(lista2)
print(np.concatenate((a1,a2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [10]:
# Zeros and ones
import numpy as np
size = tuple(map(int,input().strip().split()))
print(np.zeros(size, int))
print(np.ones(size, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [11]:
# Eye and identity
import numpy as np
np.set_printoptions(sign=' ')
print(np.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
# Array Mathematics
import numpy as np
N, M = map(int, input().split())
A = np.array([list(map(int, input().split())) for n in range(N)])
B = np.array([list(map(int, input().split())) for n in range(N)])
print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)





1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [13]:
# Floor, ceil andRint
import numpy
numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))




1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [14]:
# Sum and prod
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))




2 2
1 2
3 4
24


In [15]:
# Min and Max
N, M = map(int, input().split())
storage = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(storage, axis=1), axis=0))

4 2
2 5
3 7
1 3
4 0
3


In [16]:
# Mean, var and Std
import numpy
N,M = map(int, input().split())
l = []

for i in range(N):
    a = list(map(int, input().split()))
    l.append(a)

l = numpy.array(l)

numpy.set_printoptions(legacy='1.13')
print(numpy.mean(l, axis = 1))
print(numpy.var(l, axis = 0))
print(numpy.std(l))





2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Question 3

In [19]:
def isMagicSquare( mat) :
  n = len(mat)
  sumd1=0
  sumd2=0
  for i in range(n):
	  sumd1+=mat[i][i]
	  sumd2+=mat[i][n-i-1]
  if not(sumd1==sumd2):
	  return False
  for i in range(n):
	  sumr=0
	  sumc=0
	  for j in range(n):
	    sumr+=mat[i][j]
	    sumc+=mat[j][i]
	  if not(sumr==sumc==sumd1):
	    return False
  return True
	
mat = [ [ 2, 7, 6 ],
		[ 9, 5, 1 ],
		[ 4, 3, 8 ] ]
	
if (isMagicSquare(mat)) :
	print( "Magic Square")
else :
	print( "Not a magic Square")

Magic Square
